const draggables = {
    Bicycle: require('../../assets/Elements/bicycle.png'),
    Bus: require('../../assets/Elements/bus.png'),
    'Bicycle-man': require('../../assets/Elements/bicycle-man.png'),
    Car: require('../../assets/Elements/car-top-view.png'),
    Children: require('../../assets/Elements/children.png'),
    Person: require('../../assets/Elements/standing-up-man.png'),
    'Traffic-barrier': require('../../assets/Elements/traffic-barrier.png'),
    'Traffic-cone': require('../../assets/Elements/traffic-cone.png'),
    'Walking-person': require('../../assets/Elements/walk.png'),
    Children1: require('../../assets/Elements/children.png'),
    Person1: require('../../assets/Elements/standing-up-man.png'),
    'Traffic-barrier1': require('../../assets/Elements/traffic-barrier.png'),
    'Traffic-cone1': require('../../assets/Elements/traffic-cone.png'),
    'Walking-person1': require('../../assets/Elements/walk.png'),
    Children2: require('../../assets/Elements/children.png'),
    Person2: require('../../assets/Elements/standing-up-man.png'),
    'Traffic-barrier2': require('../../assets/Elements/traffic-barrier.png'),
    'Traffic-cone2': require('../../assets/Elements/traffic-cone.png'),
    'Walking-person2': require('../../assets/Elements/walk.png'),
    Bicycle1: require('../../assets/Elements/bicycle.png'),
    Bus1: require('../../assets/Elements/bus.png'),
    'Bicycle-man1': require('../../assets/Elements/bicycle-man.png'),
    Car1: require('../../assets/Elements/car-top-view.png'),
};

export default draggables;
